### ISSUE TITLE
[Feature request]: Custom fields

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#307] opened 2023-08-21 11:38 UTC
### Contact Details

jurre@whale-agency.com

### Is your feature request related to a problem? Please describe?

Based on multiple user requests wishing for the option to add custom fields in order to realise a customised workflow suited to their needs.

### Describe the solution you'd like

Functionality for managing custom fields.

WIP designs: https://www.figma.com/file/2XkiKJ4II7Mux6JJL9hYTm/Shelf-App-%7C-Production-Ready?type=design&node-id=6683-336967&mode=design

- Under settings, add a tab called 'Custom fields'
- Create 'Custom fields' index
- Option to create new 'Custom field' with field type 'Single line text' (more field types will follow)
- Option to delete 'Custom field' when no asset was ever created with that specific custom field active. @DonKoko  Would be good to discuss this in detail. Want to avoid data being lost.
- Option to archive 'Custom field'
- Option to either show or hide the data filled for the custom field on asset page
- Created 'Custom fields' that are active should show in the 'Create/Edit asset' view

**Comment by carlosvirreira** [comment] 2023-08-23 11:47
Ideally we can get the first custom field to be 'Single Line Text;

<img width="481" alt="Screenshot 2023-08-23 at 13 46 40" src="https://github.com/Shelf-nu/shelf.nu/assets/12449255/02eb83cf-f21b-47e8-ba64-209d0a327016">

**Comment by carlosvirreira** [comment] 2023-09-05 13:16
Hint text for 'Simple line text'

```A place to store short information for your asset. For instance: Serial numbers, notes or anything you wish. No input validation. Any text is acceptable.```

**Comment by jurrejansen** [comment] 2023-09-11 10:31
@DonKoko @hunar1312 

- [ ] When creating / editing a custom field we are still seeing the H1 'Settings' and the setting tabs. Is this view we shouldn't be seeing this

![Screenshot 2023-09-11 at 12 20 09](https://github.com/Shelf-nu/shelf.nu/assets/76112272/b6870b7d-1146-4ed7-96a1-2ab939972260)
![Screenshot 2023-09-11 at 12 22 17](https://github.com/Shelf-nu/shelf.nu/assets/76112272/a6c8c921-ad6e-4d26-a55a-6832a80873a1)

- [ ] Can we keep the placeholder H1 as "Untitled custom field" for the sake of consistency as we're also using "Untitled asset" when creating a new asset

![Screenshot 2023-09-11 at 12 26 05](https://github.com/Shelf-nu/shelf.nu/assets/76112272/e2d50878-b8dc-4697-a9c0-3279ba43230d)

**Comment by DonKoko** [comment] 2023-09-12 14:03
>  Custom fields functionality (more than 3 fields) does not work after I upgrade to a 'Plus' plan

That was related to web hooks not working properly its fixed and tested by me so I can confirm it works good now.


> When creating / editing a custom field we are still seeing the H1 'Settings' and the setting tabs. Is this view we shouldn't be seeing this

Okey this was very dirty to fix as it breaks the concept of the layout inheritance. But yeah its solved just not in a nice way.

>  Can we keep the placeholder H1 as "Untitled custom field" for the sake of consistency as we're also using "Untitled asset" when creating a new asset

I think that was a bug. Should be fixed now.

>  There is no option to delete a custom field from the index

I think you missed that part of the discussion. I took the decision to remove it as it will cause lots of issues and it's very risky for loosing data. Thats why we developed the "active" functionality.

> On Testapp > [jjqppjstcxlnyiylxq@cazlp.com](mailto:jjqppjstcxlnyiylxq@cazlp.com) > I have upgraded to a paid plan but I still got the 3 custom field error. Also, it is kind of a dark pattern to not allow the user to delete a custom field but it still counts on the custom field count rule

Yes, web hooks were not working so they were not upgrading your subscription tier

>  Required fields are not marked as required

Thanks for reminding. That functionality was merged in main and had to get implemented in the custom fields in asset for as well as the custom field form.

>  I had an account with many custom fields (8) I could not upgrade (got an error) < I know this won't happen in cases in the future but wanted to mention it.

I think this happened because of broken web hooks as well.

>  I made a required field disabled. I cannot create an item but get no response from the system. (No error). Could the two things be related?

This is super good you found this. I am super happy. It happens because the dynamic validation we make was made before we implemented "active" so it checks all fields and it should only check fields which are active. Its fixed.

@carlosvirreira  @jurrejansen Changes are being deployed to testapp: https://github.com/Shelf-nu/shelf.nu/actions/runs/6160551252

**Closed** 2023-09-19 10:34 UTC
Labels: User requested feature
