### ISSUE TITLE
[Feature request]: Bulk upload assed photo

### ISSUE THREAD

**Issue by DroneProf** [Shelf-nu/shelf.nu#1375] opened 2024-10-26 23:28 UTC
### Contact Details

rose196@purdue.edu

### Is your feature request related to a problem? Please describe?

Currently there is no way to upload the same photo for multiple assets.

### Describe the solution you'd like

Two potential solutions:
1. Externally hosted photos (I already do this in the markdown fields for FAA Registrations and WiFi QR codes).
2. Bulk edit after upload.

**Comment by DonKoko** [comment] 2024-10-28 10:25
Hey @DroneProf . Thanks for the suggestion. What you are doing already is indeed a good solution so far. 
Having multiple photos has been in our radar for a long time, we even have some old designs and an issue for it: https://github.com/Shelf-nu/shelf.nu/issues/561
However, we are not convinced by this approach as implementing something like this will again force us to put limits we don't desire to be in place. 
Ideally the solution we are considering now is having a media library where you can upload photos and use them everywhere: assets, locations, kits, etc.

We are discussing this on a daily basis trying to come up with some middle solution to give to our users in the short term, before working on the gallery. I will close this issue as a duplicate of #561 and we will keep you updated about this.

**Closed** 2024-10-28 10:30 UTC
Labels: User requested feature
