### ISSUE TITLE
[Feature request]: Enable search on Give Custody flow 

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#889] opened 2024-03-29 10:00 UTC
### Is your feature request related to a problem? Please describe?

I have many NRMs on my workspace. I am finding myself spending too much time scrolling through the list. 

### Describe the solution you'd like

It could save me a few seconds if I could search the list. Just like on Locations.

**Comment by DonKoko** [comment] 2024-04-03 15:27
This is a great idea. @rockingrohit9639 could you help us with making the dynamic search be able to work with the `CustodianSelect`?

**Comment by rockingrohit9639** [comment] 2024-04-03 15:40
Sure @DonKoko 
Is there any scenario ready for it or it is just a normal text dropdown like others ?

**Comment by carlosvirreira** [comment] 2024-04-03 15:54
No scenario for it - we (hopefully) can re-use a component for this.

**Comment by rockingrohit9639** [comment] 2024-04-03 15:55
Ok @carlosvirreira

**Comment by DonKoko** [comment] 2024-04-04 08:03
@rockingrohit9639 yeah the idea is to update the CustodianSelect component to use a DynamicSelect inside it that works like all our other DynamicSelects but for `teamMember` entity

**Comment by DonKoko** [comment] 2024-04-09 10:10
@jurrejansen @carlosvirreira this is being deployed to live: https://github.com/Shelf-nu/shelf.nu/actions/runs/8613980832

We also found another small bug related to it that we have fixed.

**Comment by DonKoko** [comment] 2024-04-25 18:25
@jurrejansen aside from that point above i think the issue is done. We dont really have a solution so I will close the issue for now.

**Closed by DonKoko** 2024-04-25 18:25 UTC
Labels: User requested feature, Priority: Low
