### ISSUE TITLE
[Feature request]: Notification for Low Asset Quantity + Request for new Custom Field Type (Quantity).

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#989] opened 2024-05-21 14:25 UTC
### Is your feature request related to a problem? Please describe?

I set up a custom field on shelf called Quantity where I keep track of stock levels. 

I instruct my users to scan a code and lower the quantity of an asset if they take something out. However, I have to manually open every single asset on my database to see the levels. This is making my workflow to not be so efficient and it takes me a lot of time to manage.

### Describe the solution you'd like

I want to set a minimum amount of the custom field type with type quantity for me to be able to get alerted. 

For example: I maintain a stock of 100 hinges and wants to receive an email notification when the quantity decreases to 10, as an example.

The email I receive can be simple:

```Hello [Admin],

Your [asset name] minimum stock alert has been reached.

Link to shelf asset

End of mail
```

### Additional context

This improvement is paired to the creation of a new custom field type with type 'Quantity' (Integer greater than or equal to 0)

**Comment by DonKoko** [comment] 2024-05-22 07:24
Isn't this a duplicate of the alerts/flags feature?

**Comment by carlosvirreira** [comment] 2024-05-22 07:50
Hi @DonKoko not really. 

Flags are to mark an item as not being usable or damaged. 
Alerts would be a similar concept but more for periodic planned maintenance. This is more related to stock level alerts.

**Closed** 2024-05-23 13:57 UTC
Labels: User requested feature
