### ISSUE TITLE
[Feature request]: Enable ability to mass apply a tag to a selection of assets

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#1306] opened 2024-09-10 20:08 UTC
### Is your feature request related to a problem? Please describe?

I have added tags that i want to apply to a large set of assets. I have to now do them one by one.

### Describe the solution you'd like

It makes sense that I would be able to do this from the actions dropdown in the asset page.

**Comment by carlosvirreira** [comment] 2024-09-11 07:54
![Screenshot 2024-09-11 at 09 53 24](https://github.com/user-attachments/assets/d1b415cf-21cb-4764-a5c7-425157a40ee2)

**Comment by DonKoko** [comment] 2024-09-16 08:31
Duplicate of #1208

**Closed by DonKoko** 2024-09-16 08:31 UTC
Labels: User requested feature
