### ISSUE TITLE
[Feature request]: Export asset inventory (backup)

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#241] opened 2023-07-21 10:39 UTC
### Contact Details

carlos@shelf.nu

### Is your feature request related to a problem? Please describe?

If I were to create a backup for myself I'd have to go through every asset and input the info onto a spreadsheet or document. Given that we currently have around 475 assets that have been put into shelf, it would take a very long time to create a backup manually.

### Describe the solution you'd like

A CSV Export would be ideal.

**Comment by carlosvirreira** [comment] 2023-07-21 10:39
This was requested by a user. I omitted its personal data and made the issue on my behalf.

**Comment by DonKoko** [comment] 2023-08-22 10:33
Duplicate of #178

**Closed** 2023-11-13 13:08 UTC
Labels: duplicate, User requested feature
