### ISSUE TITLE
[Feature request]: Booking feature feedback

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#703] opened 2024-01-31 12:47 UTC
### Is your feature request related to a problem? Please describe?

I tested the Bookings feature and want to share some thoughts.

### Describe the solution you'd like

- When inviting a new Team Member, automatic emails are not being sent
- It’s not possible to assign a booking to a NRM (could be expected behavior)
- If a booking is assigned to a custodian, when checked out the custodian’s name does not appear in the asset’s description. (see attached video)
- Bookings and checkouts are not registered in an asset’s history.

**Comment by DonKoko** [comment] 2024-01-31 14:21
> If a booking is assigned to a custodian, when checked out the custodian’s name does not appear in the asset’s description. (see attached video)

I am looking into this. Seems like a bug

> Bookings and checkouts are not registered in an asset’s history.

I think this is a great idea. @jurrejansen can you prepare some examples of what notes to add to an asset related to bookings?

**Comment by DonKoko** [comment] 2024-02-06 10:46
The custodian bug is fixed. @jurrejansen i remember seeing some designs you made. Could you share them here please?

**Comment by jurrejansen** [comment] 2024-02-06 10:51
@DonKoko here are the designs: https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=3437-54808&mode=design

They are done with updated designes of Notification elements so maybe just use the bold text instead of the pills for now

**Comment by jurrejansen** [comment] 2024-02-09 14:45
@carlosvirreira @DonKoko 

1. I understand this would be a good process to add but I don't think currently the email is confusing. The status of the booking changes to Reserved, thus the booking is confirmed. Currently we rely on the system to check if the assets are available. If we want to provide this double check + confirmation by admin we should introduce another status between Draft and Reserved states. Something like Requested, and then Admin(s) get a notification via mail (and / or In-app notification in the future) with the request to review the booking.

2. I think this would be very good to implement hmmyesh. For now and quick implementation just send the confirmation mail to all administrators of the workspace?

- [ ] When a Self-service user configures a booking and it reaches Reserved state, all administrators should receive the booking confirmation mail.

Additionally, they should also receive the rest of the mails related to the booking but the need / want for this is probably very dependent on user preference.

Regarding the second point of your extra comments. In the designs this was shown in the tooltop when hovering over the warning label. Would be good to have implemented yesh.

- [ ] When a Reserved booking includes assets that are still checked out due to another Ongoing / Overdue booking the warning label should show which Ongoing / Overdue booking

https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=1396-161183&mode=design

![Screenshot 2024-02-09 at 15 42 48](https://github.com/Shelf-nu/shelf.nu/assets/76112272/dc29605d-2743-4389-beac-323f1d7cf27b)

**Comment by jurrejansen** [comment] 2024-02-14 09:18
@DonKoko 

We've received a mail + video of one of our users reporting some weird behaviour related to booking. The user is from the US so in general the app is less responsive so some of the following issues could also be related to that.

Environment has 2 assets in inventory which both have Available status and not involved with any bookings at time of recording.

- [ ] Unable to create a booking via the initial modal after clicking New booking

https://github.com/Shelf-nu/shelf.nu/assets/76112272/7d5f3278-c693-4863-8a20-b0da0e4159de

- User clicks New booking, initial modal appears and user puts information 
- Clicks Check asset availability 
- Modal stays active and in the background 2 empty Draft bookings appear in index
- Check asset availability button becomes active again 
- User clicks button and again a empty Draft booking appears in index in the background 
- User is able to close modal by clicking the 'X' icon.


- [ ] Manage assets button does not become active when configuring one the previously created empty Draft bookings

https://github.com/Shelf-nu/shelf.nu/assets/76112272/fc394221-fb17-4057-8f0e-7431b5f0b947

https://github.com/Shelf-nu/shelf.nu/assets/76112272/581b7092-00fb-4a42-afc3-27f1ebd0537b

- User fills booking name, custodian and period
- Starts with 02/09/2024 11:00PM -> 02-11-2024 11:35 AM, no errors given
- Clicks Save but Manage assets buttons stays disabled
- Changes Start data/time to: 02/09/2024 12:00 AM, Start date must be in the future is given which is probably correct
- Changes Start data/time to: 02/09/2024 12:00 PM
- Clicks Save but Manage assets button stays disabled, when hover tooltip says:
![Screenshot 2024-02-14 at 09 35 57](https://github.com/Shelf-nu/shelf.nu/assets/76112272/e3e0468b-2f36-4547-a06b-a8be75956e8b)
- User tries 2:00 PM and 4:00 PM as start time and button stays disabled
- Changes Start time to 6:00 PM and button finally becomes active

**Comment by jurrejansen** [comment] 2024-02-14 17:49
@DonKoko @carlosvirreira  I've found a bug. You can get around not being able to Reserve a booking that includes assets that have a Checked out status because they're currently part of an Ongoing booking. 

It involves removing the Checked out asset, performing the Reserve action, and then adding the Checked out asset again. This changes the status of the Checked out asset into Available even though it's still part of the other Ongoing booking. 

The system then also doesn't block you from Checking out the original booking which results in 2 Ongoing bookings that include the same asset. The included video shows what happening. Perhaps we're giving admins too much freedom here.

https://github.com/Shelf-nu/shelf.nu/assets/76112272/56854580-3fd7-4545-9058-bfc99ff01c93

**Comment by DonKoko** [comment] 2024-02-19 14:42
> I am currently logged in as a self service user. I made a 'new booking' - selected assets and my call to action button reads 'Reserve' - I can click this and the status changes to 'reserved' - The screenshot below shows that - the title of the email reads 'Booking confirmation' - I think this is confusing and should change to 'Booking reservation for Carlos Virreira' instead of 'Booking confirmation' The booking has not been confirmed by the admin - it is just reserved. The admin will determine if the booking will be confirmed or not.


Done

> As an admin of the workspace I get no message about this 'Booking reservation' - it would be helpful for me to get a notification about this so I can go and check it - in case that I see some conflicts I can get in touch with the person attempting the reserve directly instead of at a later stage. Specially considering that an admin needs to perform the actual checkout this seems like an important email.


Done

> Searching on test app gives an error. (Tried to find a booking I had made as an admin for a self serve user)

Wasn't really aware of this high priority BUG. Has been fixed now.

**Comment by DonKoko** [comment] 2024-02-20 08:35
@jurrejansen @carlosvirreira notes related to bookings are deployed to test app. Would be nice if U can test them so I can push them to live. Please test all cases, also with bookings with multiple assets inside them.
Thanks.

**Comment by carlosvirreira** [comment] 2024-02-20 09:21
Tested on multiple assets: 
- Mutations (changes) are reflected on all assets - this works well
- Quicklink to booking page works as expected
- Emails are sent - issue with double 'minutes' has been fixed on @DonKoko branch

For me - we can ship this enhancement. Directly.

**Comment by DonKoko** [comment] 2024-02-20 10:41
All of those points have been solved and deployed. Closing this issue. For further problems encountered, lets open a new issue.

**Closed by DonKoko** 2024-02-20 10:41 UTC
Labels: User requested feature
